# Generated by Django 3.0.3 on 2020-02-28 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_attacks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Impacts',
        ),
    ]
